### ISSUE TITLE
[SET UP] Assign Roles

### ISSUE THREAD

**Issue by aribasyeda** [adamski201/Railway-Tracker#15]
## Task Description
-  Assign project roles 
   - Architect
   - Project Manager
   - Quality Assurance
- To post in channel once roles are assigned
## User Stories
- As a team member, I want to know my role and responsibilities within the project so that I can effectively contribute to achieving project goals and collaborate with other team members.
## Relevant Files [If Available]
- N/A

**Comment by SaniyaShaikhh** [comment]
Assigned Roles:
Ariba - Project Manager
Adam - QA
Isaac - QA
Saniya - Architect
