### ISSUE TITLE
[Bug] ERD Station Name character limit is 30 characters, too low for some stations

### ISSUE THREAD

**Issue by adamski201** [adamski201/Railway-Tracker#23]
Raise the varchar limit to 60 to accommodate all possible station names in the UK.

Currently, London St Pancras International at 32 characters will not be permitted as a station name.

**Comment by isaacschaessenscoleman** [comment]
<img width="1014" alt="Screenshot 2024-04-23 at 21 32 03" src="https://github.com/adamski201/Railway-Tracker/assets/84942651/d84676de-5f2f-44c0-bd23-f04387d9a441">
[DrawSQL Link](https://drawsql.app/teams/isaac-11/diagrams/railway-tracker-3)

# Changes
- Changed StationName to allow for up to 60 characters
- Changed Operator Name to allow for up to 60 characters
- Changed primary key of CancellationType to an INT - for consistency in Primary keys across the database
- Added ServiceUUID (a six letter unique id for Train services provided by the API) to the service table

- Added a ServiceTypeID foreign key in the Service Table to link to a ServiceType table (will make a github issue to see if this is necessary)

Let me know if I've missed any more!

**Comment by aribasyeda** [comment]
Amazing work guys thanks! Nitpick; we're missing a user story and relevant files (if applicable) for the ticket
