### ISSUE TITLE
[Research] Research into the ServiceType table

### ISSUE THREAD

**Issue by isaacschaessenscoleman** [adamski201/Railway-Tracker#24]
## Task Description
- Given the data in the RealTime Trains API, is there a need for a Service Type table?
<img width="1014" alt="Screenshot 2024-04-23 at 21 32 03" src="https://github.com/adamski201/Railway-Tracker/assets/84942651/bfef412a-cf2b-4e98-94f7-03b809951356">

Is the ServiceType table necessary?
Also, are there any other things (tables, column names, datatypes) to fix in the ERD?

## User Stories
- As an engineer, it's essential that I have a well thought-out schema with the right tables, columns and datatypes.

**Comment by aribasyeda** [comment]
Great work Isaac 🚀  Well done. Some feedback:
- Cancellation ID is currently linked to the Cancellation Code from the other table, did you intend to link to Cancellation ID of the other table?
- In terms of your question, it depends what ServiceType relates to - however we do need to strike a balance between normalising it and keeping it easy to understand 
Hope that helps 🚅
