### ISSUE TITLE
[Create] Create performance pipeline transform and load script

### ISSUE THREAD

**Issue by adamski201** [adamski201/Railway-Tracker#36]
Write a transform script to convert the raw data into something that conforms to our database model and then write a load script to insert it into a database client.

As a developer, we want a way to pipe our data in a clean and maintainable way so that we can make our product. 

Relevant files:
- station_performance_pipeline/transform.py
- station_performance_pipeline/load.py
- station_performance_pipeline/entities.py

**Comment by aribasyeda** [comment]
👮‍♀ Missing user story and relevant files section for the ticket @adamski201
